[files]
# exclude file list
extend-exclude = [
    "scripts/abi/baseline.txt",
]

[default.extend-words]
secon = "secon" # keep don't change it
Rabit = "Rabit"
PN = "PN"
nd = "nd"
thr = "thr"
ba = "ba"
po = "po"
