---
name       : alayalite cache
description: Cache Conan data with build type support
inputs     :
  build-type:
    description: CMAKE_BUILD_TYPE (Debug, Release, etc.)
    required: false
    default: Release
runs       :
  using: composite
  steps:
  - name: Cache Conan data
    uses: actions/cache@v4
    with:
      path: ~/.conan2
      key: conan-${{ runner.os }}-${{ inputs.build-type }}-${{ hashFiles('**/conanfile.py') }}
      restore-keys: |
        conan-${{ runner.os }}-${{ inputs.build-type }}-
        conan-${{ runner.os }}-
