# Print build configuration summary Usage: print_build_summary()
function(print_build_summary)
  message(STATUS "")
  message(STATUS "+===========================================================+")
  message(STATUS "|                  ${PROJECT_NAME} Build Configuration")
  message(STATUS "+===========================================================+")
  message(STATUS "| Build Information:")
  message(STATUS "|   - Build Type      : ${CMAKE_BUILD_TYPE}")
  message(STATUS "|   - C++ Standard    : C++${CMAKE_CXX_STANDARD}")
  message(STATUS "|   - Compiler        : ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
  message(STATUS "|   - CMake Version   : ${CMAKE_VERSION}")
  message(STATUS "|")
  message(STATUS "| Compiler Flags:")
  message(STATUS "|   - Common Flags    : ${CMAKE_CXX_FLAGS}")
  if(CMAKE_BUILD_TYPE STREQUAL "Release")
    message(STATUS "|   - Release Flags   : ${CMAKE_CXX_FLAGS_RELEASE}")
  elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "|   - Debug Flags     : ${CMAKE_CXX_FLAGS_DEBUG}")
  endif()
  message(STATUS "|   - Linker Flags    : ${CMAKE_EXE_LINKER_FLAGS}")
  message(STATUS "|")
  message(STATUS "| Directory Structure:")
  message(STATUS "|   - Source Dir      : ${PROJECT_SOURCE_DIR}")
  message(STATUS "|   - Binary Dir      : ${PROJECT_BINARY_DIR}")
  message(STATUS "|   - Runtime Output  : ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
  message(STATUS "|")
  message(STATUS "| Features:")
  message(STATUS "|   - PIC Enabled     : ${CMAKE_POSITION_INDEPENDENT_CODE}")
  message(STATUS "|   - Export Commands : ${CMAKE_EXPORT_COMPILE_COMMANDS}")
  if(MSVC)
    message(STATUS "|   - VS Toolset      : ${CMAKE_GENERATOR_TOOLSET}")
  endif()
  message(STATUS "|")
  message(STATUS "| Project Options:")
  message(STATUS "|   - Testing Mode    : ${BUILD_TESTING}")
  message(STATUS "+===========================================================+")
  message(STATUS "")
endfunction()
