[dataset]
name = "sift1m"
metric = "l2"
degree = 64
main_dimension = 128

[paths]
base = "/md1/huangliang/alaya-dev/data/sift1m/sift_base.fbin"
query = "/md1/huangliang/alaya-dev/data/sift1m/sift_query.fbin"
gt = "/md1/huangliang/alaya-dev/data/sift1m/sift_gt.ibin"
vamana = "/md1/huangliang/alaya-dev/build_graph/sift1m/alaya/R64_L100_a1.2/graph.index"
output = "/md1/huangliang/alaya-dev/build_graph/sift1m/laser"

[build]
build_threads = 48
ef_indexing = 200

# [search]
# topk = 10
# threads = 1
# beam_width = 16
# dram_budget = 1.0
# ep_num = 300
# warmup = 10
# runs = 30
# efs = [80, 90, 100, 110, 130, 150, 200, 250, 300, 400, 500]
