name: Build

on: [push, pull_request]


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      # - name: Restore Caches
      #   uses: ./.github/actions/cache-restore

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Restore Caches
        uses: ./.github/actions/cache-restore

      - name: Install cibuildwheel
        uses: pypa/cibuildwheel@v3.0.0
        env:
          CIBW_PLATFORM: linux
          # CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux_2_28_x86_64
          # CIBW_BUILD: "cp38-*"
          # CIBW_ENVIRONMENT: "CXXFLAGS='-O3 -pipe'"
          CIBW_ARCHS: aarch64

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
