name: CI-PYTHON
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-22.04-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: './pyalaya'